{% set ENV_NAME = os.environ.get('ENV_NAME', 'pagmo_env') %}

name: {{ ENV_NAME }}

channels:
  - conda-forge

dependencies:
  # All cpp stack dependencies
  - clangdev
  - cling
  - xeus
  - xeus-cling
  - pagmo
  - pygmo

  # Additional python resources
  - notebook
  - ipywidgets
  - widgetsnbextension
  - jupyter_contrib_nbextensions
  - jupyter_conda
  - python
  - scipy
  - numpy
  - pandas

environment:
  ENV_INCLUDE: {{ HOME }}/miniconda3/envs/{{ ENV_NAME }}/include